import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAttendanceTables1783007832595 implements MigrationInterface {
    name = 'CreateAttendanceTables1783007832595'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "leave_policies" DROP CONSTRAINT "FK_leave_policies_leave_type"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_dept_head"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_departments_parent"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_employees_manager"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_employees_desig"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_employees_dept"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_employees_user"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" DROP CONSTRAINT "FK_leave_ledger_leave_type"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" DROP CONSTRAINT "FK_leave_ledger_employee"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_leave_balances_leave_type"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_leave_balances_employee"`);
        await queryRunner.query(`ALTER TABLE "approval_actions" DROP CONSTRAINT "FK_approval_actions_actor"`);
        await queryRunner.query(`ALTER TABLE "approval_actions" DROP CONSTRAINT "FK_approval_actions_approval"`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" DROP CONSTRAINT "FK_workflow_steps_workflow"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "FK_approvals_user"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "FK_approvals_workflow"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_leave_applications_approval"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_leave_applications_leave_type"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_leave_applications_employee"`);
        await queryRunner.query(`ALTER TABLE "probation_records" DROP CONSTRAINT "FK_pr_employee"`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" DROP CONSTRAINT "FK_esh_employee"`);
        await queryRunner.query(`ALTER TABLE "job_changes" DROP CONSTRAINT "FK_jc_employee"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_doc_employee"`);
        await queryRunner.query(`ALTER TABLE "salary_structure_lines" DROP CONSTRAINT "FK_ssl_component"`);
        await queryRunner.query(`ALTER TABLE "salary_structure_lines" DROP CONSTRAINT "FK_ssl_structure"`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" DROP CONSTRAINT "FK_pf_employee"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" DROP CONSTRAINT "FK_ess_employee"`);
        await queryRunner.query(`ALTER TABLE "employee_benefits" DROP CONSTRAINT "FK_eb_employee"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_rp_perm"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_rp_role"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_ur_role"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_ur_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_leave_policies_leave_type_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_dept"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employees_manager"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_leave_ledger_employee_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_leave_ledger_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_leave_balances_employee_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_actions_approval_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workflow_steps_workflow_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approvals_entity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approvals_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approvals_requested_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_leave_applications_employee_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_leave_applications_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_leave_applications_dates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_probation_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_esh_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_changes_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_documents_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ssl_structure"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ess_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ess_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_holidays_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_roles_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_roles_role_id"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "UQ_leave_balances"`);
        await queryRunner.query(`CREATE TYPE "public"."shifts_type_enum" AS ENUM('fixed', 'roster')`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."shifts_type_enum" NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "grace_minutes" integer NOT NULL DEFAULT '0', "half_day_threshold_minutes" integer NOT NULL DEFAULT '240', "working_hours" numeric(4,1) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employee_id" uuid NOT NULL, "shift_id" uuid, "work_date" date NOT NULL, "is_weekend" boolean NOT NULL DEFAULT false, "is_holiday" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_schedules_employee_date" UNIQUE ("employee_id", "work_date"), CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rosters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "department_id" uuid, "cycle_days" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e1a50137614e6fe5a030145dadf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roster_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roster_id" uuid NOT NULL, "employee_id" uuid NOT NULL, "shift_id" uuid NOT NULL, "work_date" date NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_roster_assignments" UNIQUE ("roster_id", "employee_id", "work_date"), CONSTRAINT "PK_eb8f5d2389e2884711693426646" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."import_batches_type_enum" AS ENUM('attendance')`);
        await queryRunner.query(`CREATE TYPE "public"."import_batches_status_enum" AS ENUM('uploaded', 'validated', 'partially_imported', 'imported', 'failed')`);
        await queryRunner.query(`CREATE TABLE "import_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."import_batches_type_enum" NOT NULL DEFAULT 'attendance', "file_name" character varying NOT NULL, "file_url" character varying NOT NULL, "uploaded_by" uuid NOT NULL, "status" "public"."import_batches_status_enum" NOT NULL DEFAULT 'uploaded', "total_rows" integer NOT NULL DEFAULT '0', "success_rows" integer NOT NULL DEFAULT '0', "error_rows" integer NOT NULL DEFAULT '0', "column_mapping" jsonb, "started_at" TIMESTAMP WITH TIME ZONE, "finished_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6162597a2576c03e04bb2c1a2dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."import_rows_status_enum" AS ENUM('ok', 'warning', 'error')`);
        await queryRunner.query(`CREATE TABLE "import_rows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "import_batch_id" uuid NOT NULL, "row_number" integer NOT NULL, "raw" jsonb NOT NULL, "matched_employee_id" uuid, "parsed" jsonb, "status" "public"."import_rows_status_enum" NOT NULL, "message" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_45b442c5ced30d539ba20c3ec32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_records_source_enum" AS ENUM('web', 'biometric', 'device_import', 'manual')`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_records_status_enum" AS ENUM('present', 'late', 'absent', 'half_day', 'on_leave', 'holiday', 'weekend')`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employee_id" uuid NOT NULL, "work_date" date NOT NULL, "check_in_at" TIMESTAMP WITH TIME ZONE, "check_out_at" TIMESTAMP WITH TIME ZONE, "source" "public"."attendance_records_source_enum" NOT NULL, "status" "public"."attendance_records_status_enum" NOT NULL, "late_minutes" integer NOT NULL DEFAULT '0', "early_leave_minutes" integer NOT NULL DEFAULT '0', "worked_minutes" integer NOT NULL DEFAULT '0', "note" text, "import_batch_id" uuid, "regularized_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_attendance_records_employee_date" UNIQUE ("employee_id", "work_date"), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_regularizations_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "attendance_regularizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "attendance_record_id" uuid NOT NULL, "reason" text NOT NULL, "requested_by" uuid NOT NULL, "status" "public"."attendance_regularizations_status_enum" NOT NULL DEFAULT 'pending', "approval_id" uuid, "requested_check_in_at" TIMESTAMP WITH TIME ZONE, "requested_check_out_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4d999fbfe37065199d69ed89371" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TYPE "public"."accrual_method" RENAME TO "accrual_method_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_types_accrual_method_enum" AS ENUM('none', 'monthly', 'yearly')`);
        await queryRunner.query(`ALTER TABLE "leave_types" ALTER COLUMN "accrual_method" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_types" ALTER COLUMN "accrual_method" TYPE "public"."leave_types_accrual_method_enum" USING "accrual_method"::"text"::"public"."leave_types_accrual_method_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_types" ALTER COLUMN "accrual_method" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."accrual_method_old"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status" RENAME TO "user_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."users_status_enum" USING "status"::"text"::"public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."user_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."gender" RENAME TO "gender_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "gender" TYPE "public"."employees_gender_enum" USING "gender"::"text"::"public"."employees_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."gender_old"`);
        await queryRunner.query(`ALTER TYPE "public"."employment_type" RENAME TO "employment_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_employment_type_enum" AS ENUM('permanent', 'contract', 'intern', 'probation')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_type" TYPE "public"."employees_employment_type_enum" USING "employment_type"::"text"::"public"."employees_employment_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employment_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."employment_status" RENAME TO "employment_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_employment_status_enum" AS ENUM('probation', 'confirmed', 'notice_period', 'terminated', 'resigned')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_status" TYPE "public"."employees_employment_status_enum" USING "employment_status"::"text"::"public"."employees_employment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_status" SET DEFAULT 'probation'`);
        await queryRunner.query(`ALTER TYPE "public"."employee_status" RENAME TO "employee_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_status_enum" AS ENUM('active', 'on_leave', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" TYPE "public"."employees_status_enum" USING "status"::"text"::"public"."employees_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."employee_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_ledger_source" RENAME TO "leave_ledger_source_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_ledger_source_enum" AS ENUM('accrual', 'application', 'adjustment', 'carry_forward')`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" ALTER COLUMN "source" TYPE "public"."leave_ledger_source_enum" USING "source"::"text"::"public"."leave_ledger_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leave_ledger_source_old"`);
        await queryRunner.query(`ALTER TYPE "public"."approval_action_type" RENAME TO "approval_action_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."approval_actions_action_enum" AS ENUM('approve', 'reject', 'return', 'comment')`);
        await queryRunner.query(`ALTER TABLE "approval_actions" ALTER COLUMN "action" TYPE "public"."approval_actions_action_enum" USING "action"::"text"::"public"."approval_actions_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."approval_action_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."approver_type" RENAME TO "approver_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_steps_approver_type_enum" AS ENUM('line_manager', 'role', 'specific_user', 'department_head')`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" ALTER COLUMN "approver_type" TYPE "public"."workflow_steps_approver_type_enum" USING "approver_type"::"text"::"public"."workflow_steps_approver_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."approver_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."approval_entity_type" RENAME TO "approval_entity_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."workflows_entity_type_enum" AS ENUM('leave', 'requisition', 'travel_request', 'expense_claim', 'regularization')`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "entity_type" TYPE "public"."workflows_entity_type_enum" USING "entity_type"::"text"::"public"."workflows_entity_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."approvals_entity_type_enum" AS ENUM('leave', 'requisition', 'travel_request', 'expense_claim', 'regularization')`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "entity_type" TYPE "public"."approvals_entity_type_enum" USING "entity_type"::"text"::"public"."approvals_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."approval_entity_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."approval_status" RENAME TO "approval_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."approvals_status_enum" AS ENUM('pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "status" TYPE "public"."approvals_status_enum" USING "status"::"text"::"public"."approvals_status_enum"`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."approval_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_application_status" RENAME TO "leave_application_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_applications_status_enum" AS ENUM('draft', 'pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ALTER COLUMN "status" TYPE "public"."leave_applications_status_enum" USING "status"::"text"::"public"."leave_applications_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."leave_application_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."probation_status" RENAME TO "probation_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."probation_records_status_enum" AS ENUM('in_probation', 'confirmed', 'extended', 'failed')`);
        await queryRunner.query(`ALTER TABLE "probation_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "probation_records" ALTER COLUMN "status" TYPE "public"."probation_records_status_enum" USING "status"::"text"::"public"."probation_records_status_enum"`);
        await queryRunner.query(`ALTER TABLE "probation_records" ALTER COLUMN "status" SET DEFAULT 'in_probation'`);
        await queryRunner.query(`DROP TYPE "public"."probation_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employment_status_history_from_status_enum" AS ENUM('probation', 'confirmed', 'notice_period', 'terminated', 'resigned')`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" ALTER COLUMN "from_status" TYPE "public"."employment_status_history_from_status_enum" USING "from_status"::"text"::"public"."employment_status_history_from_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."employment_status_history_to_status_enum" AS ENUM('probation', 'confirmed', 'notice_period', 'terminated', 'resigned')`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" ALTER COLUMN "to_status" TYPE "public"."employment_status_history_to_status_enum" USING "to_status"::"text"::"public"."employment_status_history_to_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employment_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."employment_status_change_ref" RENAME TO "employment_status_change_ref_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employment_status_history_ref_type_enum" AS ENUM('probation', 'job_change', 'manual')`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" ALTER COLUMN "ref_type" TYPE "public"."employment_status_history_ref_type_enum" USING "ref_type"::"text"::"public"."employment_status_history_ref_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employment_status_change_ref_old"`);
        await queryRunner.query(`ALTER TYPE "public"."job_change_type" RENAME TO "job_change_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."job_changes_type_enum" AS ENUM('promotion', 'transfer', 'demotion', 'reassignment')`);
        await queryRunner.query(`ALTER TABLE "job_changes" ALTER COLUMN "type" TYPE "public"."job_changes_type_enum" USING "type"::"text"::"public"."job_changes_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."job_change_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."document_type" RENAME TO "document_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."documents_type_enum" AS ENUM('NID', 'contract', 'certificate', 'other')`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "type" TYPE "public"."documents_type_enum" USING "type"::"text"::"public"."documents_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."document_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."salary_component_type" RENAME TO "salary_component_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."salary_components_type_enum" AS ENUM('earning', 'deduction')`);
        await queryRunner.query(`ALTER TABLE "salary_components" ALTER COLUMN "type" TYPE "public"."salary_components_type_enum" USING "type"::"text"::"public"."salary_components_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."salary_component_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."salary_calc_type" RENAME TO "salary_calc_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."salary_components_calc_type_enum" AS ENUM('fixed', 'percent_of_basic', 'percent_of_gross', 'remainder')`);
        await queryRunner.query(`ALTER TABLE "salary_components" ALTER COLUMN "calc_type" TYPE "public"."salary_components_calc_type_enum" USING "calc_type"::"text"::"public"."salary_components_calc_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."salary_structure_lines_calc_type_enum" AS ENUM('fixed', 'percent_of_basic', 'percent_of_gross', 'remainder')`);
        await queryRunner.query(`ALTER TABLE "salary_structure_lines" ALTER COLUMN "calc_type" TYPE "public"."salary_structure_lines_calc_type_enum" USING "calc_type"::"text"::"public"."salary_structure_lines_calc_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."salary_calc_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."input_basis" RENAME TO "input_basis_old"`);
        await queryRunner.query(`CREATE TYPE "public"."salary_grades_basic_definition_enum" AS ENUM('basic', 'gross')`);
        await queryRunner.query(`ALTER TABLE "salary_grades" ALTER COLUMN "basic_definition" TYPE "public"."salary_grades_basic_definition_enum" USING "basic_definition"::"text"::"public"."salary_grades_basic_definition_enum"`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" DROP CONSTRAINT "UQ_pf_accounts_emp"`);
        await queryRunner.query(`ALTER TYPE "public"."pf_base" RENAME TO "pf_base_old"`);
        await queryRunner.query(`CREATE TYPE "public"."pf_accounts_pf_base_enum" AS ENUM('basic', 'gross', 'custom')`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "pf_base" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "pf_base" TYPE "public"."pf_accounts_pf_base_enum" USING "pf_base"::"text"::"public"."pf_accounts_pf_base_enum"`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "pf_base" SET DEFAULT 'basic'`);
        await queryRunner.query(`DROP TYPE "public"."pf_base_old"`);
        await queryRunner.query(`ALTER TYPE "public"."pf_status" RENAME TO "pf_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."pf_accounts_status_enum" AS ENUM('active', 'stopped')`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "status" TYPE "public"."pf_accounts_status_enum" USING "status"::"text"::"public"."pf_accounts_status_enum"`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."pf_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_salary_structures_input_basis_enum" AS ENUM('basic', 'gross')`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "input_basis" TYPE "public"."employee_salary_structures_input_basis_enum" USING "input_basis"::"text"::"public"."employee_salary_structures_input_basis_enum"`);
        await queryRunner.query(`DROP TYPE "public"."input_basis_old"`);
        await queryRunner.query(`ALTER TYPE "public"."salary_revision_reason" RENAME TO "salary_revision_reason_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_salary_structures_reason_enum" AS ENUM('initial', 'increment', 'promotion', 'revision')`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "reason" TYPE "public"."employee_salary_structures_reason_enum" USING "reason"::"text"::"public"."employee_salary_structures_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."salary_revision_reason_old"`);
        await queryRunner.query(`ALTER TYPE "public"."salary_structure_status" RENAME TO "salary_structure_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_salary_structures_status_enum" AS ENUM('draft', 'active', 'superseded')`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "status" TYPE "public"."employee_salary_structures_status_enum" USING "status"::"text"::"public"."employee_salary_structures_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."salary_structure_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."benefit_type" RENAME TO "benefit_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_benefits_type_enum" AS ENUM('gratuity', 'insurance', 'bonus', 'loan', 'transport', 'other')`);
        await queryRunner.query(`ALTER TABLE "employee_benefits" ALTER COLUMN "type" TYPE "public"."employee_benefits_type_enum" USING "type"::"text"::"public"."employee_benefits_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."benefit_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."benefit_value_type" RENAME TO "benefit_value_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_benefits_value_type_enum" AS ENUM('amount', 'percent', 'text')`);
        await queryRunner.query(`ALTER TABLE "employee_benefits" ALTER COLUMN "value_type" TYPE "public"."employee_benefits_value_type_enum" USING "value_type"::"text"::"public"."employee_benefits_value_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."benefit_value_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."holiday_type" RENAME TO "holiday_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."holidays_type_enum" AS ENUM('government', 'optional', 'company')`);
        await queryRunner.query(`ALTER TABLE "holidays" ALTER COLUMN "type" TYPE "public"."holidays_type_enum" USING "type"::"text"::"public"."holidays_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."holiday_type_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe31f79885435948a4f45d2c9b" ON "leave_balances" ("employee_id", "leave_type_id", "year") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "leave_policies" ADD CONSTRAINT "FK_145159e6d88d26843a8f9a0928b" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b" FOREIGN KEY ("parent_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_2d83c53c3e553a48dadb9722e38" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_678a3540f843823784b0fe4a4f2" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_2de5d6e4fb3345f18bc467017f0" FOREIGN KEY ("designation_id") REFERENCES "designations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_fb63e0af5f730a46e0c5ce976a8" FOREIGN KEY ("line_manager_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" ADD CONSTRAINT "FK_069494b55b17c142b13733925e7" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" ADD CONSTRAINT "FK_b69d66a659210b956f8045bb1ad" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_2f8aebce74941a2e2168e94ba68" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_d64da0a991d2f4d23d86031530c" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_actions" ADD CONSTRAINT "FK_fa7379d3909a8f14894f82d6d13" FOREIGN KEY ("approval_id") REFERENCES "approvals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" ADD CONSTRAINT "FK_02f0092e12343bfed27bb65fa89" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "FK_14f6dc2843cc9c8445d70b91478" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "FK_3483296a19c50cbf6880aba2a47" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_95054ab1386d32dfb67edf80f1f" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_b2fd131f25c1afb6471f4282ad4" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_df330adcceb2c9daff8fae3893d" FOREIGN KEY ("approval_id") REFERENCES "approvals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "probation_records" ADD CONSTRAINT "FK_93fece9215f44a2d7203178121b" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" ADD CONSTRAINT "FK_5765bc79b0a6774913e9f5257fb" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_changes" ADD CONSTRAINT "FK_3b9dadbf30ff28500f52cca19b8" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_8b60169d17455c20823032dfb38" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_structure_lines" ADD CONSTRAINT "FK_151e494900d0e519834b1b9e5f5" FOREIGN KEY ("component_id") REFERENCES "salary_components"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ADD CONSTRAINT "FK_dc9ab1a9b41c46ffec72f31f6b8" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ADD CONSTRAINT "FK_22e998cc0109a0b164f3bfa1f43" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_benefits" ADD CONSTRAINT "FK_6f762f96c97f977adf0892b2820" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_1144b8bcbcd2aa7e6a441f06792" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_0cc4f69c2960036584f8dc6ae19" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rosters" ADD CONSTRAINT "FK_29db284bafb87b14e7ded09da9d" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roster_assignments" ADD CONSTRAINT "FK_12499451eb5cdaa3cb4e23291f0" FOREIGN KEY ("roster_id") REFERENCES "rosters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roster_assignments" ADD CONSTRAINT "FK_a185cf8db3d3fd2edf8a89ab404" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roster_assignments" ADD CONSTRAINT "FK_80e17eb816c192be843b2bb07fc" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_batches" ADD CONSTRAINT "FK_97f6eb90260576d70b5190f39e4" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_rows" ADD CONSTRAINT "FK_be6b44eec36cee611ae0273d29f" FOREIGN KEY ("import_batch_id") REFERENCES "import_batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_rows" ADD CONSTRAINT "FK_0cb40406e97d29660e5502c6a2b" FOREIGN KEY ("matched_employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_f97d7be854091ef9ab5d75c0de3" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_608d6db5cc442cece0122289542" FOREIGN KEY ("import_batch_id") REFERENCES "import_batches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_43c0563d0c3d0abf666f8138bdf" FOREIGN KEY ("regularized_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_regularizations" ADD CONSTRAINT "FK_8cf8b39bc56f4341752f6637865" FOREIGN KEY ("attendance_record_id") REFERENCES "attendance_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_regularizations" ADD CONSTRAINT "FK_19b1736d108b9a5485ada732d3a" FOREIGN KEY ("requested_by") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_regularizations" ADD CONSTRAINT "FK_a99d492e6abc1fb5af07949719a" FOREIGN KEY ("approval_id") REFERENCES "approvals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "attendance_regularizations" DROP CONSTRAINT "FK_a99d492e6abc1fb5af07949719a"`);
        await queryRunner.query(`ALTER TABLE "attendance_regularizations" DROP CONSTRAINT "FK_19b1736d108b9a5485ada732d3a"`);
        await queryRunner.query(`ALTER TABLE "attendance_regularizations" DROP CONSTRAINT "FK_8cf8b39bc56f4341752f6637865"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_43c0563d0c3d0abf666f8138bdf"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_608d6db5cc442cece0122289542"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_f97d7be854091ef9ab5d75c0de3"`);
        await queryRunner.query(`ALTER TABLE "import_rows" DROP CONSTRAINT "FK_0cb40406e97d29660e5502c6a2b"`);
        await queryRunner.query(`ALTER TABLE "import_rows" DROP CONSTRAINT "FK_be6b44eec36cee611ae0273d29f"`);
        await queryRunner.query(`ALTER TABLE "import_batches" DROP CONSTRAINT "FK_97f6eb90260576d70b5190f39e4"`);
        await queryRunner.query(`ALTER TABLE "roster_assignments" DROP CONSTRAINT "FK_80e17eb816c192be843b2bb07fc"`);
        await queryRunner.query(`ALTER TABLE "roster_assignments" DROP CONSTRAINT "FK_a185cf8db3d3fd2edf8a89ab404"`);
        await queryRunner.query(`ALTER TABLE "roster_assignments" DROP CONSTRAINT "FK_12499451eb5cdaa3cb4e23291f0"`);
        await queryRunner.query(`ALTER TABLE "rosters" DROP CONSTRAINT "FK_29db284bafb87b14e7ded09da9d"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_0cc4f69c2960036584f8dc6ae19"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_1144b8bcbcd2aa7e6a441f06792"`);
        await queryRunner.query(`ALTER TABLE "employee_benefits" DROP CONSTRAINT "FK_6f762f96c97f977adf0892b2820"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" DROP CONSTRAINT "FK_22e998cc0109a0b164f3bfa1f43"`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" DROP CONSTRAINT "FK_dc9ab1a9b41c46ffec72f31f6b8"`);
        await queryRunner.query(`ALTER TABLE "salary_structure_lines" DROP CONSTRAINT "FK_151e494900d0e519834b1b9e5f5"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_8b60169d17455c20823032dfb38"`);
        await queryRunner.query(`ALTER TABLE "job_changes" DROP CONSTRAINT "FK_3b9dadbf30ff28500f52cca19b8"`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" DROP CONSTRAINT "FK_5765bc79b0a6774913e9f5257fb"`);
        await queryRunner.query(`ALTER TABLE "probation_records" DROP CONSTRAINT "FK_93fece9215f44a2d7203178121b"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_df330adcceb2c9daff8fae3893d"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_b2fd131f25c1afb6471f4282ad4"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" DROP CONSTRAINT "FK_95054ab1386d32dfb67edf80f1f"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "FK_3483296a19c50cbf6880aba2a47"`);
        await queryRunner.query(`ALTER TABLE "approvals" DROP CONSTRAINT "FK_14f6dc2843cc9c8445d70b91478"`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" DROP CONSTRAINT "FK_02f0092e12343bfed27bb65fa89"`);
        await queryRunner.query(`ALTER TABLE "approval_actions" DROP CONSTRAINT "FK_fa7379d3909a8f14894f82d6d13"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_d64da0a991d2f4d23d86031530c"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "FK_2f8aebce74941a2e2168e94ba68"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" DROP CONSTRAINT "FK_b69d66a659210b956f8045bb1ad"`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" DROP CONSTRAINT "FK_069494b55b17c142b13733925e7"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_fb63e0af5f730a46e0c5ce976a8"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_2de5d6e4fb3345f18bc467017f0"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_678a3540f843823784b0fe4a4f2"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_2d83c53c3e553a48dadb9722e38"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b"`);
        await queryRunner.query(`ALTER TABLE "leave_policies" DROP CONSTRAINT "FK_145159e6d88d26843a8f9a0928b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe31f79885435948a4f45d2c9b"`);
        await queryRunner.query(`CREATE TYPE "public"."holiday_type_old" AS ENUM('government', 'optional', 'company')`);
        await queryRunner.query(`ALTER TABLE "holidays" ALTER COLUMN "type" TYPE "public"."holiday_type_old" USING "type"::"text"::"public"."holiday_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."holidays_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."holiday_type_old" RENAME TO "holiday_type"`);
        await queryRunner.query(`CREATE TYPE "public"."benefit_value_type_old" AS ENUM('amount', 'percent', 'text')`);
        await queryRunner.query(`ALTER TABLE "employee_benefits" ALTER COLUMN "value_type" TYPE "public"."benefit_value_type_old" USING "value_type"::"text"::"public"."benefit_value_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."employee_benefits_value_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."benefit_value_type_old" RENAME TO "benefit_value_type"`);
        await queryRunner.query(`CREATE TYPE "public"."benefit_type_old" AS ENUM('gratuity', 'insurance', 'bonus', 'loan', 'transport', 'other')`);
        await queryRunner.query(`ALTER TABLE "employee_benefits" ALTER COLUMN "type" TYPE "public"."benefit_type_old" USING "type"::"text"::"public"."benefit_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."employee_benefits_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."benefit_type_old" RENAME TO "benefit_type"`);
        await queryRunner.query(`CREATE TYPE "public"."salary_structure_status_old" AS ENUM('draft', 'active', 'superseded')`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "status" TYPE "public"."salary_structure_status_old" USING "status"::"text"::"public"."salary_structure_status_old"`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."employee_salary_structures_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."salary_structure_status_old" RENAME TO "salary_structure_status"`);
        await queryRunner.query(`CREATE TYPE "public"."salary_revision_reason_old" AS ENUM('initial', 'increment', 'promotion', 'revision')`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "reason" TYPE "public"."salary_revision_reason_old" USING "reason"::"text"::"public"."salary_revision_reason_old"`);
        await queryRunner.query(`DROP TYPE "public"."employee_salary_structures_reason_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."salary_revision_reason_old" RENAME TO "salary_revision_reason"`);
        await queryRunner.query(`CREATE TYPE "public"."input_basis_old" AS ENUM('basic', 'gross')`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ALTER COLUMN "input_basis" TYPE "public"."input_basis_old" USING "input_basis"::"text"::"public"."input_basis_old"`);
        await queryRunner.query(`DROP TYPE "public"."employee_salary_structures_input_basis_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."pf_status_old" AS ENUM('active', 'stopped')`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "status" TYPE "public"."pf_status_old" USING "status"::"text"::"public"."pf_status_old"`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."pf_accounts_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."pf_status_old" RENAME TO "pf_status"`);
        await queryRunner.query(`CREATE TYPE "public"."pf_base_old" AS ENUM('basic', 'gross', 'custom')`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "pf_base" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "pf_base" TYPE "public"."pf_base_old" USING "pf_base"::"text"::"public"."pf_base_old"`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ALTER COLUMN "pf_base" SET DEFAULT 'basic'`);
        await queryRunner.query(`DROP TYPE "public"."pf_accounts_pf_base_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."pf_base_old" RENAME TO "pf_base"`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ADD CONSTRAINT "UQ_pf_accounts_emp" UNIQUE ("employee_id")`);
        await queryRunner.query(`ALTER TABLE "salary_grades" ALTER COLUMN "basic_definition" TYPE "public"."input_basis_old" USING "basic_definition"::"text"::"public"."input_basis_old"`);
        await queryRunner.query(`DROP TYPE "public"."salary_grades_basic_definition_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."input_basis_old" RENAME TO "input_basis"`);
        await queryRunner.query(`CREATE TYPE "public"."salary_calc_type_old" AS ENUM('fixed', 'percent_of_basic', 'percent_of_gross', 'remainder')`);
        await queryRunner.query(`ALTER TABLE "salary_structure_lines" ALTER COLUMN "calc_type" TYPE "public"."salary_calc_type_old" USING "calc_type"::"text"::"public"."salary_calc_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."salary_structure_lines_calc_type_enum"`);
        await queryRunner.query(`ALTER TABLE "salary_components" ALTER COLUMN "calc_type" TYPE "public"."salary_calc_type_old" USING "calc_type"::"text"::"public"."salary_calc_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."salary_components_calc_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."salary_calc_type_old" RENAME TO "salary_calc_type"`);
        await queryRunner.query(`CREATE TYPE "public"."salary_component_type_old" AS ENUM('earning', 'deduction')`);
        await queryRunner.query(`ALTER TABLE "salary_components" ALTER COLUMN "type" TYPE "public"."salary_component_type_old" USING "type"::"text"::"public"."salary_component_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."salary_components_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."salary_component_type_old" RENAME TO "salary_component_type"`);
        await queryRunner.query(`CREATE TYPE "public"."document_type_old" AS ENUM('NID', 'contract', 'certificate', 'other')`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "type" TYPE "public"."document_type_old" USING "type"::"text"::"public"."document_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."documents_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."document_type_old" RENAME TO "document_type"`);
        await queryRunner.query(`CREATE TYPE "public"."job_change_type_old" AS ENUM('promotion', 'transfer', 'demotion', 'reassignment')`);
        await queryRunner.query(`ALTER TABLE "job_changes" ALTER COLUMN "type" TYPE "public"."job_change_type_old" USING "type"::"text"::"public"."job_change_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."job_changes_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."job_change_type_old" RENAME TO "job_change_type"`);
        await queryRunner.query(`CREATE TYPE "public"."employment_status_change_ref_old" AS ENUM('probation', 'job_change', 'manual')`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" ALTER COLUMN "ref_type" TYPE "public"."employment_status_change_ref_old" USING "ref_type"::"text"::"public"."employment_status_change_ref_old"`);
        await queryRunner.query(`DROP TYPE "public"."employment_status_history_ref_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employment_status_change_ref_old" RENAME TO "employment_status_change_ref"`);
        await queryRunner.query(`CREATE TYPE "public"."employment_status_old" AS ENUM('probation', 'confirmed', 'notice_period', 'terminated', 'resigned')`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" ALTER COLUMN "to_status" TYPE "public"."employment_status_old" USING "to_status"::"text"::"public"."employment_status_old"`);
        await queryRunner.query(`DROP TYPE "public"."employment_status_history_to_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" ALTER COLUMN "from_status" TYPE "public"."employment_status_old" USING "from_status"::"text"::"public"."employment_status_old"`);
        await queryRunner.query(`DROP TYPE "public"."employment_status_history_from_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."probation_status_old" AS ENUM('in_probation', 'confirmed', 'extended', 'failed')`);
        await queryRunner.query(`ALTER TABLE "probation_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "probation_records" ALTER COLUMN "status" TYPE "public"."probation_status_old" USING "status"::"text"::"public"."probation_status_old"`);
        await queryRunner.query(`ALTER TABLE "probation_records" ALTER COLUMN "status" SET DEFAULT 'in_probation'`);
        await queryRunner.query(`DROP TYPE "public"."probation_records_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."probation_status_old" RENAME TO "probation_status"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_application_status_old" AS ENUM('draft', 'pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ALTER COLUMN "status" TYPE "public"."leave_application_status_old" USING "status"::"text"::"public"."leave_application_status_old"`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."leave_applications_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_application_status_old" RENAME TO "leave_application_status"`);
        await queryRunner.query(`CREATE TYPE "public"."approval_status_old" AS ENUM('pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "status" TYPE "public"."approval_status_old" USING "status"::"text"::"public"."approval_status_old"`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."approvals_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."approval_status_old" RENAME TO "approval_status"`);
        await queryRunner.query(`CREATE TYPE "public"."approval_entity_type_old" AS ENUM('leave', 'requisition', 'travel_request', 'expense_claim', 'regularization')`);
        await queryRunner.query(`ALTER TABLE "approvals" ALTER COLUMN "entity_type" TYPE "public"."approval_entity_type_old" USING "entity_type"::"text"::"public"."approval_entity_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."approvals_entity_type_enum"`);
        await queryRunner.query(`ALTER TABLE "workflows" ALTER COLUMN "entity_type" TYPE "public"."approval_entity_type_old" USING "entity_type"::"text"::"public"."approval_entity_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."workflows_entity_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."approval_entity_type_old" RENAME TO "approval_entity_type"`);
        await queryRunner.query(`CREATE TYPE "public"."approver_type_old" AS ENUM('line_manager', 'role', 'specific_user', 'department_head')`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" ALTER COLUMN "approver_type" TYPE "public"."approver_type_old" USING "approver_type"::"text"::"public"."approver_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_steps_approver_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."approver_type_old" RENAME TO "approver_type"`);
        await queryRunner.query(`CREATE TYPE "public"."approval_action_type_old" AS ENUM('approve', 'reject', 'return', 'comment')`);
        await queryRunner.query(`ALTER TABLE "approval_actions" ALTER COLUMN "action" TYPE "public"."approval_action_type_old" USING "action"::"text"::"public"."approval_action_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."approval_actions_action_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."approval_action_type_old" RENAME TO "approval_action_type"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_ledger_source_old" AS ENUM('accrual', 'application', 'adjustment', 'carry_forward')`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" ALTER COLUMN "source" TYPE "public"."leave_ledger_source_old" USING "source"::"text"::"public"."leave_ledger_source_old"`);
        await queryRunner.query(`DROP TYPE "public"."leave_ledger_source_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."leave_ledger_source_old" RENAME TO "leave_ledger_source"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_status_old" AS ENUM('active', 'on_leave', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" TYPE "public"."employee_status_old" USING "status"::"text"::"public"."employee_status_old"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."employees_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employee_status_old" RENAME TO "employee_status"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_status" TYPE "public"."employment_status_old" USING "employment_status"::"text"::"public"."employment_status_old"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_status" SET DEFAULT 'probation'`);
        await queryRunner.query(`DROP TYPE "public"."employees_employment_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employment_status_old" RENAME TO "employment_status"`);
        await queryRunner.query(`CREATE TYPE "public"."employment_type_old" AS ENUM('permanent', 'contract', 'intern', 'probation')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "employment_type" TYPE "public"."employment_type_old" USING "employment_type"::"text"::"public"."employment_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."employees_employment_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employment_type_old" RENAME TO "employment_type"`);
        await queryRunner.query(`CREATE TYPE "public"."gender_old" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "gender" TYPE "public"."gender_old" USING "gender"::"text"::"public"."gender_old"`);
        await queryRunner.query(`DROP TYPE "public"."employees_gender_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."gender_old" RENAME TO "gender"`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_old" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."user_status_old" USING "status"::"text"::"public"."user_status_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status_old" RENAME TO "user_status"`);
        await queryRunner.query(`CREATE TYPE "public"."accrual_method_old" AS ENUM('none', 'monthly', 'yearly')`);
        await queryRunner.query(`ALTER TABLE "leave_types" ALTER COLUMN "accrual_method" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leave_types" ALTER COLUMN "accrual_method" TYPE "public"."accrual_method_old" USING "accrual_method"::"text"::"public"."accrual_method_old"`);
        await queryRunner.query(`ALTER TABLE "leave_types" ALTER COLUMN "accrual_method" SET DEFAULT 'none'`);
        await queryRunner.query(`DROP TYPE "public"."leave_types_accrual_method_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."accrual_method_old" RENAME TO "accrual_method"`);
        await queryRunner.query(`DROP TABLE "attendance_regularizations"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_regularizations_status_enum"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_records_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_records_source_enum"`);
        await queryRunner.query(`DROP TABLE "import_rows"`);
        await queryRunner.query(`DROP TYPE "public"."import_rows_status_enum"`);
        await queryRunner.query(`DROP TABLE "import_batches"`);
        await queryRunner.query(`DROP TYPE "public"."import_batches_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."import_batches_type_enum"`);
        await queryRunner.query(`DROP TABLE "roster_assignments"`);
        await queryRunner.query(`DROP TABLE "rosters"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TYPE "public"."shifts_type_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "UQ_leave_balances" UNIQUE ("employee_id", "leave_type_id", "year")`);
        await queryRunner.query(`CREATE INDEX "IDX_user_roles_role_id" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_roles_user_id" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_role_id" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_holidays_date" ON "holidays" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb_employee" ON "employee_benefits" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ess_status" ON "employee_salary_structures" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ess_employee" ON "employee_salary_structures" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ssl_structure" ON "salary_structure_lines" ("salary_structure_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_documents_employee" ON "documents" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_changes_employee" ON "job_changes" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_esh_employee" ON "employment_status_history" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_probation_employee" ON "probation_records" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_leave_applications_dates" ON "leave_applications" ("end_date", "start_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_leave_applications_status" ON "leave_applications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_leave_applications_employee_id" ON "leave_applications" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_approvals_requested_by" ON "approvals" ("requested_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_approvals_status" ON "approvals" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_approvals_entity" ON "approvals" ("entity_id", "entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_workflow_steps_workflow_id" ON "workflow_steps" ("workflow_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_actions_approval_id" ON "approval_actions" ("approval_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_leave_balances_employee_id" ON "leave_balances" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_leave_ledger_created_at" ON "leave_ledger" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_leave_ledger_employee_id" ON "leave_ledger" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_employees_manager" ON "employees" ("line_manager_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_employees_dept" ON "employees" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_leave_policies_leave_type_id" ON "leave_policies" ("leave_type_id") `);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_ur_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_ur_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_rp_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_rp_perm" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_benefits" ADD CONSTRAINT "FK_eb_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary_structures" ADD CONSTRAINT "FK_ess_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pf_accounts" ADD CONSTRAINT "FK_pf_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_structure_lines" ADD CONSTRAINT "FK_ssl_structure" FOREIGN KEY ("salary_structure_id") REFERENCES "employee_salary_structures"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_structure_lines" ADD CONSTRAINT "FK_ssl_component" FOREIGN KEY ("component_id") REFERENCES "salary_components"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_doc_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_changes" ADD CONSTRAINT "FK_jc_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employment_status_history" ADD CONSTRAINT "FK_esh_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "probation_records" ADD CONSTRAINT "FK_pr_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_leave_applications_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_leave_applications_leave_type" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_applications" ADD CONSTRAINT "FK_leave_applications_approval" FOREIGN KEY ("approval_id") REFERENCES "approvals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "FK_approvals_workflow" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approvals" ADD CONSTRAINT "FK_approvals_user" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" ADD CONSTRAINT "FK_workflow_steps_workflow" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_actions" ADD CONSTRAINT "FK_approval_actions_approval" FOREIGN KEY ("approval_id") REFERENCES "approvals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_actions" ADD CONSTRAINT "FK_approval_actions_actor" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_leave_balances_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "FK_leave_balances_leave_type" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" ADD CONSTRAINT "FK_leave_ledger_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_ledger" ADD CONSTRAINT "FK_leave_ledger_leave_type" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_employees_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_employees_dept" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_employees_desig" FOREIGN KEY ("designation_id") REFERENCES "designations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_employees_manager" FOREIGN KEY ("line_manager_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_departments_parent" FOREIGN KEY ("parent_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_dept_head" FOREIGN KEY ("head_employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ADD CONSTRAINT "FK_leave_policies_leave_type" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
